export { default as IridiumQuality } from './quality/iridium-quality.webp'
export { default as GoldQuality } from './quality/gold-quality.webp'
export { default as SilverQuality } from './quality/silver-quality.webp'

export { default as Spring } from './seasons/Spring.webp'
export { default as Summer } from './seasons/Summer.webp'
export { default as Fall } from './seasons/Fall.webp'
export { default as Winter } from './seasons/Winter.webp'

export { default as ProductPlaceholder } from './placeholders/product-placeholder.png'
export { default as UserPlaceholder } from './placeholders/userProfile-placeholder.png'

export { default as AnimatedJunimo } from './animated/Junimo.gif'
export { default as Flag } from './animated/Calendar_Flag.gif'
export { default as Fire } from './animated/fire.gif'
export { default as UnderConstruction } from './animated/leah-elliott.gif'
export { default as NotFound } from './animated/shane-drinks.gif'

export { default as GoldCoin } from './icons/Gold.png'
export { default as RecipeIcon } from './icons/Recipe-Overlay.png'
export { default as Farmer } from './icons/farmer.png'
export { default as Rancher } from './icons/rancher.png'
export { default as Business } from './icons/cooperation.png'
export { default as FarmFresh } from './icons/farm-fresh.png'
export { default as Community } from './icons/community.png'
export { default as Cashback } from './icons/cashback.png'
export { default as BestSeller } from './icons/best-seller.png'

export { default as Store } from './store/store-with-people.png'
export { default as PierrePortrait } from './store/pierre-portrait.png'
export { default as WelcomePanel } from './store/pierre-welcome-panel.png'
export { default as StoreBuilding } from './store/Pierres_shop.png'

export { default as Map } from './Map.png'
export { default as PierreSignature } from './PierreSignature.png'